server:
  port: 4000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
  instance:
    prefer-ip-address: true #以ip注册到注册中心
spring:
  application:
    name: spring-cloud-config-server #服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhouxiong95/easybuy-config.git
          username: zhouxiong95
          password: itsource1995